// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyX971W_zm7df2_CK5m5Uo7WFRMybgWt0',
    appId: '1:872186601799:web:acd133fe3f088832abec62',
    messagingSenderId: '872186601799',
    projectId: 'webview-2553b',
    authDomain: 'webview-2553b.firebaseapp.com',
    storageBucket: 'webview-2553b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHR663GEsUV-AK0Tb0MsSRZXcVoxbDCG4',
    appId: '1:872186601799:android:a1cd3e6d97474c3dabec62',
    messagingSenderId: '872186601799',
    projectId: 'webview-2553b',
    storageBucket: 'webview-2553b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYezFhF959kFa1f5ANL5lEu-ZoZqA144c',
    appId: '1:872186601799:ios:ff890f6a92f7c548abec62',
    messagingSenderId: '872186601799',
    projectId: 'webview-2553b',
    storageBucket: 'webview-2553b.appspot.com',
    iosBundleId: 'com.example.webview',
  );
}
